import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundRoot,
    },
    header: {
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing["2xl"],
      paddingBottom: Spacing.md,
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    headerSubtitle: {
      fontSize: 14,
      color: theme.textMuted,
      marginTop: Spacing.xs,
    },
    // 搜索框样式
    searchContainer: {
      paddingHorizontal: Spacing.lg,
      marginBottom: Spacing.lg,
    },
    searchBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.xl,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 3,
    },
    searchInput: {
      flex: 1,
      marginLeft: Spacing.sm,
      fontSize: 16,
      color: theme.textPrimary,
    },
    clearButton: {
      padding: Spacing.xs,
    },
    listContent: {
      paddingHorizontal: Spacing.lg,
      paddingBottom: 120,
    },
    card: {
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius["2xl"],
      padding: Spacing.xl,
      marginBottom: Spacing.md,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 6,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: Spacing.md,
    },
    cardIcon: {
      width: 48,
      height: 48,
      borderRadius: BorderRadius.xl,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: Spacing.md,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    cardTitle: {
      flex: 1,
      fontSize: 18,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    cardMeta: {
      marginTop: Spacing.xs,
    },
    cardMetaText: {
      fontSize: 13,
      color: theme.textMuted,
    },
    cardActions: {
      flexDirection: 'row',
      gap: Spacing.sm,
      marginTop: Spacing.md,
    },
    actionBtn: {
      flex: 1,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.lg,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      gap: Spacing.xs,
    },
    checkInBtn: {
      backgroundColor: '#5ED6A0',
    },
    editBtn: {
      backgroundColor: '#EDE8FF',
    },
    deleteBtn: {
      backgroundColor: '#FFE8EE',
    },
    actionBtnText: {
      fontSize: 13,
      fontWeight: '700',
    },
    featureTag: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: Spacing.sm,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.xs,
      backgroundColor: '#EDE8FF',
      borderRadius: BorderRadius.lg,
      alignSelf: 'flex-start',
    },
    featureTagText: {
      fontSize: 12,
      color: '#5A5673',
      marginLeft: Spacing.xs,
    },
    emptyContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 100,
    },
    emptyIcon: {
      width: 80,
      height: 80,
      borderRadius: BorderRadius["2xl"],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: Spacing.lg,
      backgroundColor: '#EDE8FF',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    emptyText: {
      fontSize: 16,
      color: '#8B87A0',
      marginTop: Spacing.md,
    },
    fabButton: {
      position: 'absolute',
      right: Spacing.lg,
      bottom: 100,
      width: 64,
      height: 64,
      borderRadius: BorderRadius.full,
      backgroundColor: '#7C5CFC',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
      shadowColor: '#7C5CFC',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 8,
    },
    // Modal样式
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: BorderRadius["3xl"],
      borderTopRightRadius: BorderRadius["3xl"],
      paddingHorizontal: Spacing.xl,
      paddingTop: Spacing["2xl"],
      paddingBottom: Spacing["3xl"],
      maxHeight: '90%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.xl,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: '#2D2B3D',
    },
    closeButton: {
      width: 40,
      height: 40,
      borderRadius: BorderRadius.full,
      backgroundColor: '#EDE8FF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    input: {
      backgroundColor: '#EDE8FF',
      borderRadius: BorderRadius.xl,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      fontSize: 16,
      color: '#2D2B3D',
      marginBottom: Spacing.md,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    textArea: {
      minHeight: 100,
      textAlignVertical: 'top',
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '700',
      color: '#5A5673',
      marginBottom: Spacing.sm,
    },
    submitButton: {
      backgroundColor: '#7C5CFC',
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing["2xl"],
      borderRadius: BorderRadius.xl,
      alignItems: 'center',
      marginTop: Spacing.lg,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
      shadowColor: '#7C5CFC',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
    },
    submitButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
  });
};
