import { StyleSheet, Dimensions } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

// 获取屏幕尺寸用于响应式布局
const { width: SCREEN_WIDTH } = Dimensions.get('window');
const isSmallScreen = SCREEN_WIDTH < 375;

export const createStyles = (theme: Theme, topInset: number = 0) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundRoot,
    },
    header: {
      paddingHorizontal: Spacing.lg,
      paddingTop: topInset + Spacing.xl,  // 使用安全区域高度 + 额外间距
      paddingBottom: Spacing.md,
    },
    headerTitle: {
      fontSize: isSmallScreen ? 24 : 28,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    headerSubtitle: {
      fontSize: 14,
      color: theme.textMuted,
      marginTop: Spacing.xs,
    },
    // 搜索框样式
    searchContainer: {
      paddingHorizontal: Spacing.lg,
      marginBottom: Spacing.lg,
    },
    searchBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.xl,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 3,
    },
    searchInput: {
      flex: 1,
      marginLeft: Spacing.sm,
      fontSize: 16,
      color: theme.textPrimary,
    },
    clearButton: {
      padding: Spacing.xs,
    },
    listContent: {
      paddingHorizontal: Spacing.lg,
      paddingBottom: 120,
    },
    card: {
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius["2xl"],
      padding: Spacing.lg,
      marginBottom: Spacing.md,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 6,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: Spacing.sm,
    },
    cardIcon: {
      width: 36,
      height: 36,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: Spacing.sm,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    cardTitle: {
      flex: 1,
      fontSize: 15,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    // 标题旁的图标按钮
    headerIconBtn: {
      width: 28,
      height: 28,
      borderRadius: BorderRadius.full,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: Spacing.xs,
      backgroundColor: theme.backgroundTertiary,
    },
    cardMeta: {
      marginTop: 2,
    },
    cardMetaText: {
      fontSize: 12,
      color: theme.textMuted,
    },
    // 时间和特征同行
    tagsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      marginTop: Spacing.sm,
      flexWrap: 'wrap',
    },
    dateTag: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      backgroundColor: '#E0F8EC',
      borderRadius: BorderRadius.md,
    },
    dateTagText: {
      fontSize: 11,
      color: theme.clayGreen,
      marginLeft: 4,
      fontWeight: '600',
    },
    featureTag: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.md,
    },
    featureTagText: {
      fontSize: 11,
      color: theme.textSecondary,
      marginLeft: 4,
    },
    distanceTag: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      backgroundColor: '#FFF3E0',
      borderRadius: BorderRadius.md,
    },
    distanceTagText: {
      fontSize: 11,
      color: '#E65100',
      marginLeft: 4,
    },
    notesHint: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      backgroundColor: '#F3E5F5',
      borderRadius: BorderRadius.md,
    },

    emptyContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 100,
    },
    emptyIcon: {
      width: 80,
      height: 80,
      borderRadius: BorderRadius["2xl"],
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: Spacing.lg,
      backgroundColor: theme.backgroundTertiary,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    emptyText: {
      fontSize: 16,
      color: theme.textMuted,
      marginTop: Spacing.md,
    },
    fabButton: {
      position: 'absolute',
      right: Spacing.lg,
      bottom: 100,
      width: 64,
      height: 64,
      borderRadius: BorderRadius.full,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 8,
    },
    // Modal样式
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: theme.backgroundDefault,
      borderTopLeftRadius: BorderRadius["3xl"],
      borderTopRightRadius: BorderRadius["3xl"],
      paddingHorizontal: Spacing.xl,
      paddingTop: Spacing["2xl"],
      paddingBottom: Spacing["3xl"],
      maxHeight: '90%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.xl,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    closeButton: {
      width: 40,
      height: 40,
      borderRadius: BorderRadius.full,
      backgroundColor: theme.backgroundTertiary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    input: {
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.xl,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      fontSize: 16,
      color: theme.textPrimary,
      marginBottom: Spacing.md,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    textArea: {
      minHeight: 100,
      textAlignVertical: 'top',
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.textSecondary,
      marginBottom: Spacing.sm,
    },
    submitButton: {
      backgroundColor: theme.primary,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing["2xl"],
      borderRadius: BorderRadius.xl,
      alignItems: 'center',
      marginTop: Spacing.lg,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
    },
    submitButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    // 时间选择器样式
    datePickerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.xl,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      marginBottom: Spacing.md,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
    },
    datePickerText: {
      fontSize: 16,
      color: theme.textPrimary,
    },
    datePickerBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    // 备注弹窗样式
    notesModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Spacing.xl,
    },
    notesModalContent: {
      width: '100%',
      maxWidth: 360,
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius["2xl"],
      overflow: 'hidden',
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.25,
      shadowRadius: 24,
      elevation: 12,
    },
    notesModalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: Spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    notesModalIcon: {
      width: 40,
      height: 40,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: Spacing.md,
    },
    notesModalTitle: {
      flex: 1,
      fontSize: 16,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    notesCloseBtn: {
      width: 32,
      height: 32,
      borderRadius: BorderRadius.full,
      backgroundColor: theme.backgroundTertiary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    notesModalBody: {
      padding: Spacing.lg,
      maxHeight: 300,
    },
    notesText: {
      fontSize: 15,
      lineHeight: 24,
      color: theme.textSecondary,
    },
  });
};
